// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDGggcsvKMOTS-esHvtUOfyKNk1HBqWrM',
    appId: '1:468280729237:web:635a5f212d1607f6f6059c',
    messagingSenderId: '468280729237',
    projectId: 'futrent-a9c4f',
    authDomain: 'futrent-a9c4f.firebaseapp.com',
    storageBucket: 'futrent-a9c4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpaOMquWJkVu9MMhs3luT9w8Qp26RqpnM',
    appId: '1:468280729237:android:d8791160b22297f5f6059c',
    messagingSenderId: '468280729237',
    projectId: 'futrent-a9c4f',
    storageBucket: 'futrent-a9c4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6nsI5FviEFKnN29ytXFyhSV8HeCiEOCI',
    appId: '1:468280729237:ios:f73b85a794d52e7ef6059c',
    messagingSenderId: '468280729237',
    projectId: 'futrent-a9c4f',
    storageBucket: 'futrent-a9c4f.appspot.com',
    androidClientId: '468280729237-u6s5cta450fb2nulcf650qemdhd2b6e0.apps.googleusercontent.com',
    iosClientId: '468280729237-13dlrbit1cv4jhsv277mmesvum7v7fb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.futrentMobile',
  );
}
