class Texts {
  static const String descriptionEstabilishment =
      'Bem-vindo à "FutArena Recreativa" - o local perfeito para os amantes do futebol e da boa diversão! Nossa quadra de futebol de última geração oferece uma experiência única para jogadores de todos os níveis, desde os iniciantes até os mais experientes. Localizada em um ambiente acolhedor e moderno, a FutArena Recreativa possui uma quadra impecavelmente mantida, equipada com grama sintética de alta qualidade para garantir partidas emocionantes e seguras. Nossas instalações são ideais para eventos esportivos, torneios amigáveis entre amigos ou treinos regulares. Após uma partida intensa, convidamos você a relaxar e celebrar suas conquistas em nosso quiosque exclusivo. O "Pós-Jogo Lounge" oferece uma variedade de opções deliciosas, desde petiscos rápidos até refeições substanciais para satisfazer todos os gostos. Desfrute de uma ampla seleção de bebidas refrescantes enquanto compartilha histórias e risadas com seus companheiros de equipe. Nossa equipe dedicada está sempre à disposição para garantir que sua experiência na FutArena Recreativa seja inesquecível. Seja para comemorar uma vitória, relaxar após um dia agitado ou simplesmente se divertir com amigos, nossa quadra de futebol e quiosque pós-jogo são o destino perfeito para a comunidade esportiva local. Venha fazer parte da energia vibrante da FutArena Recreativa - onde a paixão pelo futebol se encontra com momentos sociais memoráveis!';

  static const String commentRomario =
      'Minha experiência na FutArena Recreativa foi simplesmente incrível! Desde o momento em que pisei na quadra, fiquei impressionado com a qualidade das instalações. A grama sintética de alta qualidade proporcionou um jogo suave e seguro, tornando a experiência de jogar futebol ainda mais prazerosa. O atendimento da equipe foi excepcional. Eles foram prestativos e amigáveis, garantindo que tudo corresse perfeitamente durante o nosso tempo na quadra. As instalações estavam impecavelmente limpas e bem cuidadas, o que adicionou um toque extra à atmosfera acolhedora. Após a partida, decidimos relaxar no "Pós-Jogo Lounge" e ficamos surpresos com a variedade de opções deliciosas disponíveis. Os petiscos eram saborosos, e a seleção de bebidas atendeu a todos os gostos. Foi o lugar perfeito para confraternizar com os amigos e compartilhar as emoções do jogo.';

  static const String answerRomario =
      'Caro Romário, Ficamos extremamente satisfeitos ao ler suas palavras sobre sua experiência na FutArena Recreativa! É uma alegria saber que você apreciou cada aspecto do nosso estabelecimento, desde a qualidade da quadra até o ambiente descontraído do Pós-Jogo Lounge. Nosso objetivo é proporcionar momentos memoráveis aos nossos clientes, e saber que atingimos isso com sucesso para você é muito gratificante. Agradecemos também por reconhecer o empenho da nossa equipe em garantir que sua visita fosse impecável. Cada elogio é uma motivação extra para continuarmos oferecendo serviços da mais alta qualidade. Estamos especialmente felizes por saber que você considera a FutArena Recreativa como um local ideal para eventos esportivos. Estamos comprometidos em proporcionar um espaço propício para torneios amigáveis e competições emocionantes. Esperamos ansiosos por recebê-lo novamente em breve para mais partidas emocionantes e momentos agradáveis no Pós-Jogo Lounge. A FutArena Recreativa está sempre de portas abertas para você e seus amigos! Agradecemos pela sua preferência e por escolher a FutArena Recreativa como seu destino esportivo. Até a próxima! Atenciosamente, Equipe FutArena Recreativa';
}
